<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Durai-LT" name="com.whertheworkis.qa.testcase.OccupationPopupWindowTest" tests="6" failures="0" timestamp="8 Apr 2020 11:09:58 GMT" time="1.030" errors="1">
  <testcase name="popupCloseButtonTest" time="0.093" classname="com.whertheworkis.qa.testcase.OccupationPopupWindowTest">
    <error type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at org.testng.Assert.assertEquals(Assert.java:296)
	at com.whertheworkis.qa.testcase.OccupationPopupWindowTest.popupCloseButtonTest(OccupationPopupWindowTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- popupCloseButtonTest -->
  <testcase name="occupationProfilePieChartPresentTest" time="0.054" classname="com.whertheworkis.qa.testcase.OccupationPopupWindowTest"/>
  <testcase name="projectedLineChartPresentTest" time="0.059" classname="com.whertheworkis.qa.testcase.OccupationPopupWindowTest"/>
  <testcase name="occupationPopupTitleTest" time="0.035" classname="com.whertheworkis.qa.testcase.OccupationPopupWindowTest"/>
  <testcase name="mouseHoverOnLineChartTest" time="0.394" classname="com.whertheworkis.qa.testcase.OccupationPopupWindowTest"/>
  <testcase name="mouseHoverOnPieChartTest" time="0.395" classname="com.whertheworkis.qa.testcase.OccupationPopupWindowTest"/>
</testsuite> <!-- com.whertheworkis.qa.testcase.OccupationPopupWindowTest -->
